name: Tests
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  pull_request:
    branches:
      - "**" # all
    paths-ignore:
      - "**/*.md"

  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout longblock
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: false
      - name: Setup Go ^1.22.5
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22.5"
      - name: 🔎 Check compilation
        run: go mod tidy
      - name: Run tests
        run: make test
